# Enter your zone id and account id, then rename this file to wrangler.toml.
# Consider removing wrangler.toml from the .gitignore file
type = "webpack"
name = "example"
account_id = ""
workers_dev = true
zone_id = ""
webpack_config = "webpack.config.js"
route = 'example.nhancv.com/*'
usage_model = ''
compatibility_flags = []
compatibility_date = "2021-11-06"

[site]
entry-point = "./"
bucket = "./dist/static"
